# Use root/example as user/password credentials
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017 # to be only exposed in testing env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMINUSERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMINPASSWORD:-example}
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379 # to be only exposed in testing env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-example}"]
    volumes:
      - redis-data:/data
    environment:
      REDIS_USERNAME: ${REDIS_USERNAME:-default}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-example}

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env.sample
      - .env.dev
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/home/root/
    command: |
      sh -c "uv run python manage.py migrate && uv run python manage.py runserver 0.0.0.0:8000"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.sample
      - .env.dev
    depends_on:
      - backend
      - mongo
      - redis
    command: ["uv", "run", "celery", "-A", "chitragupta", "worker", "--loglevel=info"]
    volumes:
      - .:/home/root/
      
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.sample
      - .env.dev
    depends_on:
      - backend
      - mongo
      - redis
    command: ["uv", "run", "celery", "-A", "chitragupta", "beat", "--loglevel=info"]

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5555:5555
    env_file:
      - .env.sample
      - .env.dev
    depends_on:
      - backend
      - mongo
      - redis
      - celery_beat
    command: ["uv", "run", "celery", "-A", "chitragupta", "flower", "--port=5555"]
    volumes:
      - .:/home/root/

volumes:
  redis-data:
  mongo-data: