# Use root/example as user/password credentials
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017 # to be only exposed in testing env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMINUSERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMINPASSWORD:-example}
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379 # to be only exposed in testing env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-example}"]
    volumes:
      - redis-data:/data
    environment:
      REDIS_USERNAME: ${REDIS_USERNAME:-default}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-example}

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env.sample
    depends_on:
      - mongo
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.sample
    depends_on:
      - backend
      - mongo
      - redis
    command: ["uv", "run", "celery", "-A", "chitragupta", "worker", "--loglevel=info"]

volumes:
  redis-data:
  mongo-data: