name: "Build and Push Dev/main Docker Images to DockerHub"

on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  build-and-push-dev-docker-images:
    runs-on: ubuntu-latest
    steps:
      
      - name: Branch Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and publish version tag image
      - name: Build and push version tag docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend/
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chitragupta:${{ github.head_ref || github.ref_name }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push commit hash docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend/
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chitragupta:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
      