name: "Release: Build and Push Docker Images to DockerHub"

permissions:
  contents: read

on:
  release:
    types: [published]

jobs:
  build-and-push-main-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Build and publish version tag image
      - name: Build and push version tag docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend/
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chitragupta:${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64

      # Build and publish latest tag image
      - name: Build and push latest docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend/
          file: ./backend/DockerFile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chitragupta:latest
          platforms: linux/amd64,linux/arm64
